### ISSUE TITLE
Incorporate logo

### ISSUE THREAD

**Issue by lewlefton** [UnBlockEd-Project/unblocked-site#14]
We have a working logo. I've attached it here as a png 
![Unblocked](https://user-images.githubusercontent.com/6842658/107294878-4b5e8600-6a3c-11eb-9d9c-417b66dd0c70.png)

svg version in the slack channel (github doesn't like svg)

This should be put onto the page, maybe replacing the 4 L shaped orange dots?  

Also it could be used as a favicon for browser location bars.

**Comment by adithya-gatech** [comment]
Closed, changed favicon as well
