### ISSUE TITLE
HIGH PRIORITY - Gardner Logo missing and remove KCTCS logo and reference.

### ISSUE THREAD

**Issue by lewlefton** [UnBlockEd-Project/unblocked-site#16]
This partner logo needs to be added.  
![gardner institute logo Transparent](https://user-images.githubusercontent.com/6842658/107426593-70133600-6aee-11eb-8618-4d0518b17617.png)

**Comment by lewlefton** [comment]
Also, need to remove the Kentucky CTCS logo and reference to them since they haven't officially agreed yet.

**Comment by adithya-gatech** [comment]
Resolved
