### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by adithya-gatech** [UnBlockEd-Project/unblocked-site#6]
Fix the contact form to not only say content. Have contact form link to some backend to create mailing list

**Comment by lewlefton** [comment]
Contact Form headings need to be replaced from "Message" to be Name, Email, and Message.  @adithya-gatech  I thought we made that change already?

@rkukjk said the data was going to a Google Sheet, can you share a link, or better yet, maybe we can put the sheet into the Project Google Drive?  

Submit button on Contact Us form doesn't actually seem to be working.

Also, as mentioned in the Sprint spreadsheet, this form can later change to send to info@unblocked.org which @haydenfree  was going to set up on the hosting service and determine who should be the recipient of these messages.

**Comment by rkukjk** [comment]
@lewlefton Sir I don't think I have access to the Project Google Drive folder. Here is the link instead: https://docs.google.com/spreadsheets/d/1vQZryec2pWFmBr_gij3nJKu013o2ET-zkWgeR5f7xqk/edit?usp=sharing

**Comment by lewlefton** [comment]
Here is the link for our collaborative documents:
This is the project Google Drive

https://drive.google.com/drive/folders/1x_f7Ytdbesbbni9xGxUmauz4Tx_e44LD?usp=sharing

Could we use that for the Contact Form results for now until we get the email working?

**Comment by lewlefton** [comment]
@adithya-gatech @rkukjk @haydenfree  any update on the form?  It still says message everywhere and submit doesn't work

**Comment by rkukjk** [comment]
I am still having problems with the contact form. It only shows timestamp on the google sheets when it is also supposed to include the name, email, and message of the person who contacted.

**Comment by lewlefton** [comment]
@rkukjk Thanks for your efforts.  At this point, if the contact form isn't working, I'd say we comment it out and remove it from the site for now.  Maybe we can just put the email in the footer of the page with a sentence like 

"For further information email contact@bic-unblocked.org"
